source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/HorizonteNovasMidias/ios-pod-specs.git'

platform :ios, '9.0'
use_frameworks!

target 'Birdsong_Example' do
  pod 'Birdsong', :path => '../'

  target 'Birdsong_Tests' do
    inherit! :search_paths

    
  end
end
